apiVersion: v1
kind: Pod
metadata:
  name: auth-ms
  labels:
    app: myapp
    type: front-end
spec:
  imagePullSecrets:
    - name: github-pull
  containers:
    - name: auth-ms
      image: ghcr.io/nicatbekirzade/auth-ms:1.1
