apiVersion: v1
kind: Service
metadata:
  name: secret-dotfiles-svc
spec:
  ports:
  - port: 9095
    protocol: TCP
    targetPort: 9095
  selector:
    app: myapp
    type: front-end
  type: NodePort
