apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image
    env:
    - name: MYSQL_SERVICE_HOST
      value: mysql.payroll.svc.cluster.local
    - name: MYSQL_SERVICE_PORT
      value: "3306"
