apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: username-binding
  namespace: default
subjects:
- kind: User
  name: username
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: username-role
  apiGroup: rbac.authorization.k8s.io

