kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-admin
rules:
  - apiGroups: ["storage.k8s.io/v1", ""]
    resources: ["persistentvolumes", "storageclasses"]
    verbs: ["create", "list", "get", "delete"]
