apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-prod-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /data/rabbit-prod
    server: <ip-of-nfs-server>
