apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  namespace: <specify-the-namespace>
  name: production-rabbitmqcluster
spec:
  persistence:
    storageClassName: nfs-storage
    storage: 10Gi
  replicas: 1
  resources:
    requests: {}
  rabbitmq:
          additionalConfig: |
                  log.console.level = info
                  channel_max = 700
                  default_user= guest 
                  default_pass = guest
                  default_user_tags.administrator = true
  service:
    type: LoadBalancer
