apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraform-pvc
  namespace: tdac
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: terraform-pv
