apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraform
  namespace: tdac
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      type: front-end
  template:
    metadata:
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws-credentials
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws-credentials
        - name: AWS_REGION
          value: us-east-2
      - name: terraform
        image: ghcr.io/tda-centre/terraform:1.2
        volumeMounts:
        - mountPath: /tda-terraform
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: terraform-pvc
      imagePullSecrets:
       - name: github-pull
      nodeName: tdatestworker01 # Use this if you have not configured NFS server
