apiVersion: v1
kind: Service
metadata:
  name: terraform
  namespace: tdac
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp
    type: front-end
  type: ClusterIP
