apiVersion: v1
kind: PersistentVolume
metadata:
  name: terraform-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tda-terraform/"
