apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  usages:
    - digital signature
    - key encipherment
    - server auth
  signerName: kubernetes.io/kube-apiserver-client
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQTJDZWVHWGRXdWhyZ0FTaENteWx0UjMweXAxc0ZCb3dtOHBtakdNMnlrSDhXCmtZNGJuMFR3eDkxUUtsNGYzM09PZk5DVXNXdXpmbXV6bEo2cHg3ZzVhK3hYNk01NHVacFRMaWpnWXlZL0I3NDIKN0hONlFLcWx5bnF5Q1l0bG1oWjFxU1luVXByWTNWc3M4TzJWMWFYVC9ORmhiQk84MnRsdG1QUzhwclhuYWZqTAp3VzVJWlFId3c4Qk5QTFd2SmxUbHdrd2VLZExqdmlSbm1oSmgvNjZrRUlsMzlIaXVaR2g5TkFkQm5xT2tNTGY2ClRKOS9JK0k2QzZUWmlSNG5Ra3BXKzZONjIrNFJpWUVJZ2NRejNqdEFDY3ZqdHhDOWhOWGdSMXg3WWcvdkpuVDQKSU51amFBTGcvR3hYaWIxV3JrUWFPM3RSTFU4bCtYVlQrUHdxVnhUc2FRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQkMyOWVmNkxLRGsrWi9kK3Yxa0pZZjFlcVlJdWpPbk00R2tQcTg2MERzUmdlQm1BT1VKCkdpRTVHQlFmWXZLUlBFTUMzbVFUanU4a2FrQ29jalBqK2IxN0s4NlgyOTBvYzNUODhndkg0U1FOWGRBZTRrTkEKSDFNVG9LQ1BDbS9QSjFMa1lCVXIyNkozUXJjSmVZYWJnNXdmWXM2V2VTbWhzOXJCRTk4Q1VMcmdLd2FwQTZsMwo3OUtQay9ON251Mm1oMXROdTdVL0JoYzVLV21EYnUvR0NyR1dSRTN4V1VFM1paU2oyNUpsSlNQSXlKdUxLSXc2CmZBQkd2K2h5UDYrRklLWjFOVk8rREtiZGU2Z0VJQUhWZDhaSXNuUjBBU3IxYjVxNVdOemNHelRuZ3VJVk8zeUYKRDVUUXFWMVFQRXJDTiswTWs1VFArZklPSksxMmttRE1FTDA9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
