apiVersion: v1
kind: Pod
metadata:
   name: nginx
   labels:
     app: myapp
     tier: frontend
spec:
   containers:
   - name: nginx
     image: nginx
   affinity:
     nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: size
             operator: In # or NotIn
             values:
             - Large      # or Small with operator NotIn  
             - Medium
# The in operator means we can place a pod to any node whose label size has any value in the "values" section (in this case Large and Medium)
# Operator "Exists" will ensure to place a pod to any node with a label set (there may be many nodes with no label set). In this case, we dont have to set "values"
# section.
