apiVersion: v1
kind: Pod
metadata:
   name: nginx
   labels:
     app: myapp
     tier: frontend
spec:
   containers:
   - name: nginx
     image: nginx
   affinity:
     nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: size
             operator: In
             values:
             - Large
